[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 921600
upload_speed = 460800

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; The esp32-camera driver is bundled with the ESP32 Arduino core
